%% Generate the transmission site
fq = 4.0e9; % 3.5 GHz 5G band

tx = txsite("Name","ICT-City (BS)", ...
    "Latitude",60.448131, ...
    "Longitude",22.297403, ...
    "TransmitterPower",24, ...
    "TransmitterFrequency",fq,...
    "AntennaHeight", 30);
show(tx)

%% Calculate the coverage (Omnidirectional antenna)
%Propagation model (Longley-Rice)
pm = propagationModel('longley-rice');

coverage(tx, 'PropagationModel',pm, ...
    'ReceiverAntennaHeight',1, ...
    'SignalStrengths',-120:-5)

